#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# and responds to SIGTERM with "I am invincible!!!"

# Define the trap directly
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
